# Generated by Django 4.2.9 on 2026-04-27 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret', models.CharField(help_text='TOTP secret key (base32 encoded)', max_length=255)),
                ('is_enabled', models.BooleanField(default=False, help_text='Is 2FA active for this user?')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When 2FA was first verified', null=True)),
                ('backup_codes', models.TextField(blank=True, help_text='Backup codes for account recovery (comma-separated, space-separated pairs)')),
                ('backup_codes_used', models.JSONField(default=list, help_text='List of used backup code indices')),
                ('disabled_at', models.DateTimeField(blank=True, help_text='When 2FA was disabled', null=True)),
                ('disabled_reason', models.CharField(blank=True, help_text='Why 2FA was disabled', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '2FA Configuration',
                'verbose_name_plural': '2FA Configurations',
                'db_table': 'two_factor_auth',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuthLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('setup_initiated', 'Setup Initiated'), ('setup_verified', '2FA Setup Verified'), ('setup_cancelled', 'Setup Cancelled'), ('enabled', '2FA Enabled'), ('disabled', '2FA Disabled'), ('token_verified', 'OTP Token Verified'), ('token_failed', 'OTP Token Failed'), ('backup_code_used', 'Backup Code Used'), ('backup_code_invalid', 'Backup Code Invalid'), ('recovery_attempted', 'Recovery Attempted')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('details', models.JSONField(default=dict, help_text='Event-specific data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '2FA Audit Log',
                'verbose_name_plural': '2FA Audit Logs',
                'db_table': 'two_factor_auth_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='two_factor__user_id_371a4e_idx'), models.Index(fields=['event_type', '-created_at'], name='two_factor__event_t_d43e0d_idx')],
            },
        ),
    ]
