# Generated by Django 4.2.9 on 2026-05-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_twofactorauth_twofactorauthlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactorauth',
            name='backup_codes',
        ),
        migrations.RemoveField(
            model_name='twofactorauth',
            name='secret',
        ),
        migrations.AddField(
            model_name='twofactorauth',
            name='_backup_codes_encrypted',
            field=models.TextField(blank=True, db_column='backup_codes_encrypted', help_text='Backup codes encriptados (DO NOT ACCESS DIRECTLY - use .backup_codes property)'),
        ),
        migrations.AddField(
            model_name='twofactorauth',
            name='_secret_encrypted',
            field=models.TextField(blank=True, db_column='secret_encrypted', help_text='TOTP secret encriptado (DO NOT ACCESS DIRECTLY - use .secret property)'),
        ),
    ]
