# Generated by Django 4.2.9 on 2026-03-24 20:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
        ('subscriptions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('hci_key', models.CharField(blank=True, max_length=80)),
                ('document_type_code', models.CharField(choices=[('01', 'Factura Electronica'), ('03', 'Nota de Credito Electronica'), ('04', 'Tiquete Electronico')], default='01', max_length=2)),
                ('consecutive_number', models.CharField(blank=True, max_length=20)),
                ('numeric_key', models.CharField(blank=True, max_length=50)),
                ('receiver_name', models.CharField(blank=True, max_length=255)),
                ('receiver_tax_id', models.CharField(blank=True, max_length=50)),
                ('receiver_email', models.EmailField(blank=True, max_length=254)),
                ('sale_condition', models.CharField(choices=[('01', 'Contado'), ('02', 'Credito'), ('99', 'Otros')], default='01', max_length=2)),
                ('payment_method_code', models.CharField(choices=[('01', 'Efectivo'), ('02', 'Tarjeta'), ('03', 'Transferencia'), ('04', 'SINPE Movil'), ('99', 'Otros')], default='03', max_length=2)),
                ('currency', models.CharField(default='CRC', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('paid', 'Paid'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('hacienda_status', models.CharField(choices=[('not_sent', 'Not Sent'), ('processing', 'Processing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('error', 'Error')], default='not_sent', max_length=20)),
                ('hacienda_message', models.TextField(blank=True)),
                ('hacienda_track_id', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('xml_payload', models.TextField(blank=True)),
                ('xml_response', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_electronic_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FiscalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(choices=[('CR', 'Costa Rica')], default='CR', max_length=2)),
                ('legal_name', models.CharField(max_length=255)),
                ('commercial_name', models.CharField(blank=True, max_length=255)),
                ('tax_id', models.CharField(max_length=50, unique=True)),
                ('tax_activity_code', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('hacienda_environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('hacienda_username', models.CharField(blank=True, max_length=255)),
                ('hacienda_password', models.CharField(blank=True, max_length=255)),
                ('certificate_file', models.CharField(blank=True, max_length=255)),
                ('certificate_pin', models.CharField(blank=True, max_length=100)),
                ('branch_code', models.CharField(default='001', max_length=3)),
                ('terminal_code', models.CharField(default='00001', max_length=5)),
                ('invoice_sequence', models.PositiveIntegerField(default=1)),
                ('credit_note_sequence', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_fiscal_profiles',
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('billing_model', models.CharField(choices=[('subscription', 'Subscription'), ('usage', 'Usage'), ('hybrid', 'Hybrid')], default='subscription', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchedulerJobLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=100)),
                ('triggered_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('skipped', 'Skipped'), ('error', 'Error')], default='running', max_length=20)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_scheduler_job_logs',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('currency', models.CharField(default='CRC', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual'), ('one_time', 'Unico')], default='monthly', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5)),
                ('cabys_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='billing.productcatalog')),
            ],
            options={
                'db_table': 'billing_product_prices',
                'ordering': ['product__name', 'amount'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='CRC', max_length=3)),
                ('method', models.CharField(choices=[('sinpe', 'SINPE'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.electronicinvoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='organizations.organization')),
            ],
            options={
                'db_table': 'billing_payment_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('cabys_code', models.CharField(blank=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.electronicinvoice')),
            ],
            options={
                'db_table': 'billing_invoice_lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='electronicinvoice',
            name='fiscal_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.fiscalprofile'),
        ),
        migrations.AddField(
            model_name='electronicinvoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_invoices', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='electronicinvoice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.productcatalog'),
        ),
        migrations.AddField(
            model_name='electronicinvoice',
            name='product_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.productprice'),
        ),
        migrations.AddField(
            model_name='electronicinvoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electronic_invoices', to='subscriptions.subscription'),
        ),
        migrations.CreateModel(
            name='RevenueSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField()),
                ('currency', models.CharField(default='CRC', max_length=3)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('invoices_issued', models.PositiveIntegerField(default=0)),
                ('invoices_paid', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_snapshots', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_snapshots', to='billing.productcatalog')),
            ],
            options={
                'db_table': 'billing_revenue_snapshots',
                'ordering': ['-snapshot_date', 'product__name'],
                'unique_together': {('snapshot_date', 'product', 'organization', 'currency')},
            },
        ),
    ]
