# Generated by Django 4.2.9 on 2026-03-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalprofile',
            name='client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fiscalprofile',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
