# Generated by Django 4.2.9 on 2026-03-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_fiscalprofile_client_id_fiscalprofile_client_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
