# Generated by Django 4.2.9 on 2026-03-24 22:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_paymentrecord_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('report_type', models.CharField(choices=[('billing_summary', 'Billing Summary'), ('collections_snapshot', 'Collections Snapshot')], default='billing_summary', max_length=40)),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='daily', max_length=20)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hour', models.PositiveSmallIntegerField(default=7)),
                ('minute', models.PositiveSmallIntegerField(default=0)),
                ('timezone', models.CharField(default='America/Costa_Rica', max_length=64)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_recurring_report_schedules',
                'ordering': ['name'],
            },
        ),
    ]
