# Generated by Django 4.2.9 on 2026-05-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_recurringreportschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalprofile',
            name='certificate_pin',
        ),
        migrations.RemoveField(
            model_name='fiscalprofile',
            name='client_secret',
        ),
        migrations.RemoveField(
            model_name='fiscalprofile',
            name='hacienda_password',
        ),
        migrations.AddField(
            model_name='fiscalprofile',
            name='_certificate_pin_encrypted',
            field=models.TextField(blank=True, db_column='certificate_pin_encrypted', help_text='Certificado PIN encriptado (DO NOT ACCESS DIRECTLY - use .certificate_pin property)'),
        ),
        migrations.AddField(
            model_name='fiscalprofile',
            name='_client_secret_encrypted',
            field=models.TextField(blank=True, db_column='client_secret_encrypted', help_text='OAuth2 client secret encriptado (DO NOT ACCESS DIRECTLY - use .client_secret property)'),
        ),
        migrations.AddField(
            model_name='fiscalprofile',
            name='_hacienda_password_encrypted',
            field=models.TextField(blank=True, db_column='hacienda_password_encrypted', help_text='Contraseña Hacienda encriptada (DO NOT ACCESS DIRECTLY - use .hacienda_password property)'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='method',
            field=models.CharField(choices=[('sinpe', 'SINPE'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('cash', 'Cash'), ('check', 'Check'), ('deposit', 'Deposit'), ('other', 'Other')], max_length=20),
        ),
    ]
