# Generated by Django 6.0.6 on 2026-07-01 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_fiscalprofile_certificate_pin_and_more'),
        ('products', '0003_productentitlementauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatalog',
            name='system_product',
            field=models.ForeignKey(blank=True, help_text='Producto SaaS administrado por AdminApps que este item factura.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_catalog_items', to='products.productsystem'),
        ),
    ]
