# Generated by Django 4.2.9 on 2026-04-17 02:55

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio Base')),
                ('currency', models.CharField(default='MXN', max_length=3, verbose_name='Moneda')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], default='monthly', max_length=20, verbose_name='Ciclo de Facturación')),
                ('max_users', models.PositiveIntegerField(default=5, verbose_name='Máximo de Usuarios')),
                ('max_documents', models.PositiveIntegerField(default=100, verbose_name='Máximo de Documentos')),
                ('max_storage_mb', models.PositiveIntegerField(default=500, verbose_name='Almacenamiento (MB)')),
                ('max_organizations', models.PositiveIntegerField(default=1, verbose_name='Máximo de Organizaciones')),
                ('modules_included', models.JSONField(default=list, help_text='Lista de módulos: sca, sie, asb, spm, documents, risks, objectives', verbose_name='Módulos Incluidos')),
                ('features', models.JSONField(default=list, verbose_name='Características')),
                ('ai_analysis_enabled', models.BooleanField(default=False, verbose_name='Análisis IA Habilitado')),
                ('ai_monthly_quota', models.PositiveIntegerField(default=0, verbose_name='Cuota Mensual de IA')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Plan Destacado')),
                ('is_trial_available', models.BooleanField(default=True, verbose_name='Prueba Disponible')),
                ('trial_days', models.PositiveIntegerField(default=14, verbose_name='Días de Prueba')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'db_table': 'plans',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', 'Periodo de Prueba'), ('active', 'Activa'), ('past_due', 'Pago Vencido'), ('cancelled', 'Cancelada'), ('expired', 'Expirada'), ('suspended', 'Suspendida')], default='trial', max_length=20)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('current_users', models.PositiveIntegerField(default=0)),
                ('current_documents', models.PositiveIntegerField(default=0)),
                ('current_storage_mb', models.PositiveIntegerField(default=0)),
                ('ai_usage_this_month', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('external_subscription_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('card', 'Tarjeta de Crédito/Débito'), ('bank_transfer', 'Transferencia Bancaria'), ('cash', 'Efectivo'), ('check', 'Cheque'), ('deposit', 'Deposito Bancario'), ('paypal', 'PayPal'), ('other', 'Otro')], max_length=20)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre/Alias')),
                ('card_last_four', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('card_exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número de Factura')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('paid', 'Pagada'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('line_items', models.JSONField(default=list, verbose_name='Conceptos')),
                ('notes', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.organization', verbose_name='Organización')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscriptions.subscription', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'invoices',
                'ordering': ['-issued_at'],
            },
        ),
    ]
