# Generated by Django 6.0.6 on 2026-06-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='modules_included',
            field=models.JSONField(default=list, help_text='Lista de módulos: sca, sie, asb, spm, documents, risks, objectives, medsupplier', verbose_name='Módulos Incluidos'),
        ),
    ]
