# Generated by Django 4.2.9 on 2026-05-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_landing_analytics_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='landinganalyticsevent',
            new_name='landing_ana_event_d_a6e96f_idx',
            old_name='landing_ana_event_d_becf14_idx',
        ),
        migrations.RenameIndex(
            model_name='landinganalyticsevent',
            new_name='landing_ana_event_n_664d42_idx',
            old_name='landing_ana_event_n_a61111_idx',
        ),
    ]
