# Generated by Django 6.0.6 on 2026-07-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_rename_landing_ana_event_d_becf14_idx_landing_ana_event_d_a6e96f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationapikey',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationapikey',
            name='last_used_service',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
