# Generated by Django 4.2.9 on 2026-01-27 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ISOStandard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('version', models.CharField(default='2015', max_length=20, verbose_name='Versión')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(default='shield-check', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Color')),
                ('status', models.CharField(choices=[('development', 'En Desarrollo'), ('beta', 'Beta'), ('active', 'Activo'), ('deprecated', 'Descontinuado')], default='development', max_length=20)),
                ('is_base', models.BooleanField(default=False, verbose_name='Es Módulo Base')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Mensual')),
                ('annual_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Anual')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('clauses_count', models.PositiveIntegerField(default=0, verbose_name='Número de Cláusulas')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('released_at', models.DateField(blank=True, null=True, verbose_name='Fecha de Lanzamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estándar ISO',
                'verbose_name_plural': 'Estándares ISO',
                'db_table': 'iso_standards',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('suspended', 'Suspendido'), ('trial', 'Prueba'), ('expired', 'Expirado')], default='trial', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('activated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Activación')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración')),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_activated', to=settings.AUTH_USER_MODEL)),
                ('iso_standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_assignments', to='products.isostandard')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iso_modules', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Módulo de Organización',
                'verbose_name_plural': 'Módulos de Organizaciones',
                'db_table': 'organization_modules',
                'unique_together': {('organization', 'iso_standard')},
            },
        ),
        migrations.CreateModel(
            name='ModuleActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('enabled', 'Habilitado'), ('disabled', 'Deshabilitado'), ('trial_started', 'Prueba Iniciada'), ('trial_ended', 'Prueba Terminada'), ('expired', 'Expirado'), ('renewed', 'Renovado')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='products.organizationmodule')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Módulo',
                'verbose_name_plural': 'Logs de Módulos',
                'db_table': 'module_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
