# Generated by Django 6.0.6 on 2026-06-27 16:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_initial_products(apps, schema_editor):
    ProductSystem = apps.get_model('products', 'ProductSystem')
    initial_products = [
        {
            'code': 'ISO_SMART',
            'name': 'ISO Smart',
            'slug': 'iso-smart',
            'description': 'Sistema SaaS para gestion ISO y QMS-ready operations.',
            'product_type': 'saas',
            'status': 'active',
            'billing_enabled': True,
            'icon': 'shield-check',
        },
        {
            'code': 'MEDSUPPLIER',
            'name': 'ISO Smart MedSupplier',
            'slug': 'iso-smart-medsupplier',
            'description': 'Workspace Supplier-Customer para medical devices y cadenas reguladas.',
            'product_type': 'saas',
            'status': 'active',
            'billing_enabled': True,
            'icon': 'stethoscope',
        },
    ]
    for product in initial_products:
        ProductSystem.objects.update_or_create(
            code=product['code'],
            defaults=product,
        )


def unseed_initial_products(apps, schema_editor):
    ProductSystem = apps.get_model('products', 'ProductSystem')
    ProductSystem.objects.filter(code__in=['ISO_SMART', 'MEDSUPPLIER']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationfeatureflag'),
        ('products', '0001_initial'),
        ('subscriptions', '0002_alter_plan_modules_included'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('product_type', models.CharField(choices=[('saas', 'SaaS'), ('module', 'Module'), ('service', 'Service'), ('bundle', 'Bundle')], default='saas', max_length=20)),
                ('status', models.CharField(choices=[('development', 'En Desarrollo'), ('beta', 'Beta'), ('active', 'Activo'), ('deprecated', 'Descontinuado'), ('retired', 'Retirado')], default='development', max_length=20)),
                ('billing_enabled', models.BooleanField(default=True)),
                ('launch_url', models.URLField(blank=True)),
                ('api_base_url', models.URLField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_products', to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'Producto/Sistema',
                'verbose_name_plural': 'Productos/Sistemas',
                'db_table': 'product_systems',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationProductEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('trial', 'Prueba'), ('active', 'Activo'), ('suspended', 'Suspendido'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='trial', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('modules_enabled', models.JSONField(blank=True, default=list)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_entitlements_activated', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_entitlements', to='organizations.organization')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_entitlements', to='subscriptions.plan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_entitlements', to='subscriptions.subscription')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_entitlements', to='products.productsystem')),
            ],
            options={
                'verbose_name': 'Entitlement de Producto',
                'verbose_name_plural': 'Entitlements de Producto',
                'db_table': 'organization_product_entitlements',
                'ordering': ['organization__name', 'product__name'],
                'unique_together': {('organization', 'product')},
            },
        ),
        migrations.RunPython(seed_initial_products, unseed_initial_products),
    ]
