# Generated by Django 6.0.6 on 2026-07-01 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationfeatureflag'),
        ('products', '0002_productsystem_organizationproductentitlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEntitlementAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Creado'), ('enabled', 'Activado'), ('disabled', 'Deshabilitado'), ('trial_started', 'Trial iniciado'), ('updated', 'Actualizado'), ('plan_changed', 'Plan cambiado'), ('validated', 'Validado')], max_length=30)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_entitlement_audit_events', to=settings.AUTH_USER_MODEL)),
                ('entitlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='products.organizationproductentitlement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_entitlement_audit_logs', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlement_audit_logs', to='products.productsystem')),
            ],
            options={
                'verbose_name': 'Auditoria de Entitlement',
                'verbose_name_plural': 'Auditorias de Entitlements',
                'db_table': 'product_entitlement_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='product_ent_organiz_f09d15_idx'), models.Index(fields=['product', '-created_at'], name='product_ent_product_a4e1e9_idx'), models.Index(fields=['action', '-created_at'], name='product_ent_action_4400ab_idx')],
            },
        ),
    ]
