# Generated by Django 4.2.9 on 2026-01-27 16:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Razón Social')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='RFC/NIT')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Principal')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado/Provincia')),
                ('country', models.CharField(default='México', max_length=100, verbose_name='País')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('industry', models.CharField(choices=[('manufacturing', 'Manufactura'), ('technology', 'Tecnología'), ('healthcare', 'Salud'), ('finance', 'Finanzas'), ('education', 'Educación'), ('construction', 'Construcción'), ('retail', 'Comercio'), ('services', 'Servicios'), ('government', 'Gobierno'), ('other', 'Otro')], default='services', max_length=50, verbose_name='Industria')),
                ('size', models.CharField(choices=[('micro', 'Micro (1-10 empleados)'), ('small', 'Pequeña (11-50 empleados)'), ('medium', 'Mediana (51-250 empleados)'), ('large', 'Grande (251-1000 empleados)'), ('enterprise', 'Corporativo (1000+ empleados)')], default='small', max_length=20, verbose_name='Tamaño')),
                ('employees_count', models.PositiveIntegerField(default=1, verbose_name='Número de Empleados')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Color Primario')),
                ('secondary_color', models.CharField(default='#1E40AF', max_length=7, verbose_name='Color Secundario')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('suspended', 'Suspendida'), ('trial', 'Periodo de Prueba')], default='trial', max_length=20, verbose_name='Estado')),
                ('max_users', models.PositiveIntegerField(default=5, verbose_name='Máximo de Usuarios')),
                ('max_documents', models.PositiveIntegerField(default=100, verbose_name='Máximo de Documentos')),
                ('max_storage_mb', models.PositiveIntegerField(default=500, verbose_name='Almacenamiento Máximo (MB)')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de Periodo de Prueba')),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de Suscripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('iso_standards', models.JSONField(default=list, verbose_name='Estándares ISO')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email Invitado')),
                ('role', models.CharField(default='user', max_length=30, verbose_name='Rol Asignado')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, verbose_name='Mensaje Personal')),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Invitación',
                'verbose_name_plural': 'Invitaciones',
                'db_table': 'organization_invitations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='organizations.organization')),
                ('module_sca_enabled', models.BooleanField(default=True, verbose_name='SCA Habilitado')),
                ('module_sie_enabled', models.BooleanField(default=True, verbose_name='SIE Habilitado')),
                ('module_asb_enabled', models.BooleanField(default=True, verbose_name='ASB Habilitado')),
                ('module_spm_enabled', models.BooleanField(default=True, verbose_name='SPM Habilitado')),
                ('module_documents_enabled', models.BooleanField(default=True, verbose_name='Documentos Habilitado')),
                ('module_risks_enabled', models.BooleanField(default=True, verbose_name='Riesgos Habilitado')),
                ('module_objectives_enabled', models.BooleanField(default=True, verbose_name='Objetivos Habilitado')),
                ('ai_auto_analysis', models.BooleanField(default=False, verbose_name='Análisis Automático')),
                ('ai_analysis_frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='weekly', max_length=20, verbose_name='Frecuencia de Análisis')),
                ('notify_risk_critical', models.BooleanField(default=True)),
                ('notify_risk_high', models.BooleanField(default=True)),
                ('notify_objective_deadline', models.BooleanField(default=True)),
                ('notify_document_expiry', models.BooleanField(default=True)),
                ('notify_audit_reminder', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('system', 'Sistema')], default='dark', max_length=20, verbose_name='Tema')),
                ('language', models.CharField(default='es', max_length=10, verbose_name='Idioma')),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20, verbose_name='Formato de Fecha')),
                ('auto_backup_enabled', models.BooleanField(default=False, verbose_name='Backup Automático')),
                ('backup_frequency', models.CharField(default='weekly', max_length=20, verbose_name='Frecuencia de Backup')),
                ('last_backup_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Backup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Organización',
                'verbose_name_plural': 'Configuraciones de Organizaciones',
                'db_table': 'organization_settings',
            },
        ),
    ]
