# Generated by Django 4.2.9 on 2026-04-27

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationFeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=80, verbose_name='Clave')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('enabled', models.BooleanField(default=False, verbose_name='Habilitada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Si está vacío, aplica como valor global por defecto.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'db_table': 'organization_feature_flags',
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('key', 'organization'), name='uniq_feature_flag_scope')],
            },
        ),
    ]
